### ISSUE TITLE
Whether your package can work in Chinese Language or not ? 

### ISSUE THREAD

**Issue by spzhuang** [zgornel/StringAnalysis.jl#13]

**Comment by zgornel** [comment]
I do not know what particularities of Chinese are as I am totally unfamiliar with it.
It would be interesting if you could test it out and see what could be supported. Feel free to report and issues with minimal working examples and they will be looked upon in due time.

**Comment by spzhuang** [comment]
Thanks for your reply.
The main problem for Chinese is we haven't a available token tool base on Julia language. I list a few of examples:
If `StringAnalysis.tokens` apply in a whole Chinese sentense:
![图片](https://user-images.githubusercontent.com/35912166/124211133-35eb1500-db1f-11eb-80e7-ec4634829b3f.png)
We get the return but it hasn't  been tokenized at all.
If `StringAnalysis.tokens` apply in a tokenized Chinese sentense (I tokenize it by myself):
![图片](https://user-images.githubusercontent.com/35912166/124211361-8f534400-db1f-11eb-86c2-3ec41685aae0.png)
The result can work effective.
In a word, I think `StringAnalysis` can work in Chinese only if we have a available Chinese token tool.

**Comment by zgornel** [comment]
`StringAnalysis.jl` supports using [WordTokenizers.jl](https://github.com/JuliaText/WordTokenizers.jl) as well. There is an example In the README.md of `WordTokenizers.jl` for using it with a Japanese tokenizer. I do not know what is the complexity required to implement a Chinese tokenizer but probably its best to implement it in another package and build an API conforming to `WordTokenizers.jl`; from there it can be used with `StringAnalysis.jl`.

EDIT: Found this https://github.com/hack1nt0/ChineseTokenizers.jl but did not look into it ;) Perhaps it is what you are looking for.
