### ISSUE TITLE
Version up to have a working version for Julia 1.7?

### ISSUE THREAD

**Issue by svilupp** [zgornel/StringAnalysis.jl#15]
Thank you for the library!

I was wondering if it would be possible to version up and publish the main branch version to have a working version for Julia 1.7+ in the package registry?

Why: I'm keen to have the fix for the `undefined write_sub` error, which has been fixed by [PR #14](https://github.com/zgornel/StringAnalysis.jl/pull/14). 

Impact: It's sub-optimal to always have to install StringAnalysis from the main branch instead of a simple `]add StringAnalysis`

**Comment by zgornel** [comment]
Updated and [merged](https://github.com/JuliaRegistries/General/pull/62119#event-6785696763). Cheers
