### ISSUE TITLE
StringAnalysis doesn't support musl libc

### ISSUE THREAD

**Issue by jpsamaroo** [zgornel/StringAnalysis.jl#9]
SnowballBuilder doesn't have any released tarballs for musl libc, which precludes support for Alpine Linux. It seems like SnowballBuilder is pretty outdated; would there be interest in a JLL package instead?

**Comment by aviks** [comment]
There is also Snowball.jl. You don't need to use the jll directly.

**Comment by zgornel** [comment]
I think the `.jll` is a better option. @jpsamaroo if you have the time to make a pull, it would be great. I'm pretty busy these days but im keeping an eye open for easy maintenance. @aviks I was aware of that however,  integrating `Snowball.jl` was more complicated
